services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-config.hcl:/vault/config/vault.hcl
      - ./vault-data:/vault/data
    command: server
